### ISSUE TITLE
Chrome/Web Extension FS Support?

### ISSUE THREAD

**Issue by unit-404** [JiangJie/happy-opfs#1]
I working on Web Application, with OPFS (PWA), Chrome or Web Extension FS (bit different API), and NodeJS Promise FS (Electron). Web app with most multi-platform support. And I would to request about adding Web Extension FS support. 

Bit more about API:
https://developer.mozilla.org/en-US/docs/Web/API/FileSystem

**Comment by JiangJie** [comment]
I don't think it's a good idea to support it in this project, since quite a few parts of the Web File System API have been marked as deprecated.
Maybe you can find another package or implement it yourself.
